" Might need to run vim -u ~/.config/vim/vimrc the first time to get the vimrc to load

" Internet told me to do this
set nocompatible

set rtp^=~/.config/vim

set tabstop=4

" Load Plug?
"set rtp+=~/.config/vim/autoload
"source ~/.config/vim/autoload/plug.vim

" FZF set up
" set rtp+=usr/local/bin/fzf
source /usr/share/doc/fzf/examples/plugin/fzf.vim " TODO make this local

"source ~/.config/vim/autoload/autotag.vim
source ~/.config/vim/plugins/autotag.vim

" Update tags on file save? For c and cpp only
" Apparently this only works on some files, but it's compelling!
"au FileType {c,cpp} au BufWritePost <buffer> silent ! [ -e tags ] &&
    "\ ( awk -F'\t' '$2\!="%:gs/'/'\''/"{print}' tags ; ctags -f- '%:gs/'/'\''/' )
    "\ | sort -t$'\t' -k1,1 -o tags.new && mv tags.new tags

"call plug#begin()

"Plug '/usr/local/bin/fzf'

"call plug#end()

" Get pretty
syntax on

" Line Numbers
set number
set relativenumber
set shiftwidth=4

filetype plugin on
set omnifunc=syntaxcomplete#Complete " Idk if I need this

" colorscheme elflord
set background=dark
colorscheme quiet



" Rebind Leader
let mapleader = "\<Space>"

""" Keybinds
" FZF find files my beloved (one day check out https://github.com/junegunn/fzf.vim?tab=readme-ov-file)
nmap <leader>sf :FZF<Return>
